# Application
spring.application.name=SmartFit

# H2 Database
spring.datasource.url=jdbc:h2:mem:smartfitdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# SQL init
spring.sql.init.mode=always

# JWT
jwt.secret=SmartFitGymSecretKeyForJWTTokenGeneration2025ExamFinalPSP1234567890
